remote_theme: pages-themes/architect@v0.2.0

plugins:
  - jekyll-remote-theme

title: "Syed Kounain Abbas Rizvi's Blog"
description: "Sharing insights, tutorials, and experiences from my journey as a web developer. Explore practical solutions, tools, and techniques for mastering modern web technologies."
baseurl: ""
url: "https://abbasmashaddy72.github.io"
